server:
  port: 9091
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      #最大等待毫秒数
      max-wait: 10000
      #最大连接数量，设置0为没有限制
      max-idle: 10
      #最大连接活动数
      max-active: 50
      #数据库连接池初始化连接数
      initial-size: 5
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package: com.springboot.study.common.config
swagger:
  enable: true